# -*- coding: utf-8 -*-
"""corrigido KutralNet training models .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oZr50WAIedsiT5ZPOvY7_LyaYdtT6Q3r

Clonar repositorio
"""

!git clone https://github.com/Kaique-Passos/FireDetection.git

"""Dependencies install"""

!apt-get -qq install imagemagick # required for image transform
!pip install git+https://github.com/angel-ayala/octconv.git # octave convolution library
!pip install thop # model profiler

# work on repository folder
import os
os.chdir('/content/FireDetection')  #change dir

"""Obtener datasets"""

#firenet
os.chdir('/content/FireDetection/datasets/FireNetDataset')  #change dir
#!./download.sh

"""### Solução alternativa: Usando `gdown` (Python)"""

# Instale a biblioteca gdown (se ainda não estiver instalada)
!pip install gdown

import gdown
import os
import shutil
from PIL import Image

# --- Configure o diretório de trabalho se for necessário ---
# Certifique-se de estar no diretório correto para salvar o dataset
# Por exemplo, para o FireNetDataset:
os.chdir('/content/FireDetection/datasets/FireNetDataset')

# arquivo training.zip do meu google drive
FILE_ID = '1pd_i5gCslQJ7KfXxhgGKbdzrZJ_NEAhU'
OUTPUT_FILENAME = 'training.zip'

#Limpando downloads anteriores
pastas = [
    "Test_Dataset1__Our_Own_Dataset",
    "Training",
    "Training Dataset"
]

for pasta in pastas:
    if os.path.exists(pasta):
        shutil.rmtree(pasta)
        print(f'Pasta "{pasta}" deletada.')
    else:
        print(f'Pasta "{pasta}" não existe.')



print(f"Tentando baixar o arquivo com ID '{FILE_ID}' para '{OUTPUT_FILENAME}'...")

try:
    # O gdown.download automaticamente lida com a página de aviso de arquivos grandes
    gdown.download(id=FILE_ID, output=OUTPUT_FILENAME, quiet=False, fuzzy=True)
    print(f"Download de '{OUTPUT_FILENAME}' concluído!")

    # Tentar descompactar e mover (adapte conforme seu download.sh original)
    if os.path.exists(OUTPUT_FILENAME):
        print("Descompactando...")
        !unzip -qq -o {OUTPUT_FILENAME} # -o para sobrescrever, -d para especificar o destino
        # Exemplo de como seu download.sh original move:
        !mv 'Training Dataset' "Training"

        print("Limpando arquivo zip...")
        os.remove(OUTPUT_FILENAME)
    else:
        print(f"Erro: Arquivo '{OUTPUT_FILENAME}' não encontrado após o download.")

    img = Image.open("Training/Fire/fire1.jpg")
    img.convert("RGB").save("Training/Fire/fire1.jpg")

    img = Image.open("Training/NoFire/nofire630.jpg")
    img.convert("RGB").save("Training/NoFire/nofire630.jpg")

    img = Image.open("Training/NoFire/nofire631.jpg")
    img.convert("RGB").save("Training/NoFire/nofire631.jpg")

    img = Image.open("Training/NoFire/nofire650.jpg")
    img.convert("RGB").save("Training/NoFire/nofire650.jpg")

    img = Image.open("Training/NoFire/nf1238.jpg")
    img.convert("RGB").save("Training/NoFire/nf1238.jpg")

except Exception as e:
    print(f"Ocorreu um erro durante o download: {e}")


# Arquivo testing.zip do meu google drive
FILE_ID = '1XyGMfhNQ95EHWp6owMTUN32zj48t8fl8'
OUTPUT_FILENAME = 'testing.zip'

print(f"Tentando baixar o arquivo com ID '{FILE_ID}' para '{OUTPUT_FILENAME}'...")

try:
    # O gdown.download automaticamente lida com a página de aviso de arquivos grandes
    gdown.download(id=FILE_ID, output=OUTPUT_FILENAME, quiet=False, fuzzy=True)
    print(f"Download de '{OUTPUT_FILENAME}' concluído!")

    # Tentar descompactar e mover (adapte conforme seu download.sh original)
    if os.path.exists(OUTPUT_FILENAME):
        print("Descompactando...")
        !unzip -qq -o {OUTPUT_FILENAME} # -o para sobrescrever, -d para especificar o destino
        # Exemplo de como seu download.sh original move:
        !mv 'Test_Dataset1__Our_Own_Dataset' "Test"

        print("Limpando arquivo zip...")
        os.remove(OUTPUT_FILENAME)
    else:
        print(f"Erro: Arquivo '{OUTPUT_FILENAME}' não encontrado após o download.")

except Exception as e:
    print(f"Ocorreu um erro durante o download: {e}")


# Após o download, você pode voltar ao diretório original se necessário
# os.chdir('/content/kutralnet')

#fismo
os.chdir('/content/FireDetection/datasets/FiSmoDataset')  #change dir
#!./download.sh

#Limpando downloads anteriores
pastas = [
    "FiSmo-Images"
]

for pasta in pastas:
    if os.path.exists(pasta):
        shutil.rmtree(pasta)
        print(f'Pasta "{pasta}" deletada.')
    else:
        print(f'Pasta "{pasta}" não existe.')


# Arquivo Fismo-images.zip do meu google drive
FILE_ID = '1WJsbp6ceTaMwtB9UQATy_n6I23Gr0rp7'
OUTPUT_FILENAME = 'FiSmo-Images.zip'

print(f"Tentando baixar o arquivo com ID '{FILE_ID}' para '{OUTPUT_FILENAME}'...")

try:
    # O gdown.download automaticamente lida com a página de aviso de arquivos grandes
    gdown.download(id=FILE_ID, output=OUTPUT_FILENAME, quiet=False, fuzzy=True)
    print(f"Download de '{OUTPUT_FILENAME}' concluído!")

    # Tentar descompactar e mover (adapte conforme seu download.sh original)
    if os.path.exists(OUTPUT_FILENAME):
        print("Descompactando...")
        !unzip -qq -o {OUTPUT_FILENAME} # -o para sobrescrever, -d para especificar o destino

        # Tira as imagens de dentro da pasta FiSmo-Images
        origem = "FiSmo-Images"
        for item in os.listdir(origem):
            shutil.move(os.path.join(origem, item), "./")

        print("Limpando arquivo zip...")
        os.remove(OUTPUT_FILENAME)
    else:
        print(f"Erro: Arquivo '{OUTPUT_FILENAME}' não encontrado após o download.")

except Exception as e:
    print(f"Ocorreu um erro durante o download: {e}")

# back to home
os.chdir('/content/FireDetection')  #change dir

# for Google Drive use
#from google.colab import drive
# check if GDrive is mounted
#drive_root = '/content/drive'

#if not os.path.exists(drive_root):
#    drive.mount(drive_root)
#else:
#    print('GDrive already mounted at', drive_root)

#root_path = os.path.join(drive_root, 'My Drive') # os.getcwd()
#print('Root path in', root_path)

# Commented out IPython magic to ensure Python compatibility.
import matplotlib
import matplotlib.pyplot as plt
# %matplotlib inline

"""Training"""

import os
import time
import torch
import argparse
import importlib
import numpy as np
from contextlib import redirect_stdout
from datasets import available_datasets
from utils.training import train_model
from utils.training import plot_history
from utils.training import save_history
from utils.models import models_conf, get_config

# Seed
seed_val = 666
use_cuda = torch.cuda.is_available()
torch.manual_seed(seed_val)
np.random.seed(seed_val)

if use_cuda:
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

# choose model
base_model = 'kutralnet_mobileoct'
version = None#1
# train config
batch_size = 32
epochs = 10
shuffle_dataset = True
preload_data = True # load dataset on-memory
# model pre-configuration
config = get_config(base_model)
img_dims = config['img_dims']
model_name = config['model_name']

# common preprocess
transform_train = config['preprocess_train']
transform_val = config['preprocess_val']

# dataset read
dataset_name = 'fismo'
# Get the dataset configuration dictionary first
dataset_config = available_datasets[dataset_name]
# Then, get the actual dataset class from the configuration
base_dataset_class = dataset_config['class']

train_data = base_dataset_class(transform=transform_train, preload=preload_data)
val_data = base_dataset_class(purpose='val', transform=transform_val, preload=preload_data)

num_classes = len(train_data.labels)

# model selection
if base_model in models_conf:
    module = importlib.import_module(config['module_name'])
    fire_model = getattr(module, config['class_name'])
    model = fire_model(classes=num_classes)
else:
    raise ValueError('Must choose a model first [firenet, octfiresnet, resnet, kutralnet (and lite variations)]')

# optimizers
criterion = config['criterion'] #nn.CrossEntropyLoss()
opt_args = {'params': model.parameters()}#,'eps': 1e-7}
opt_args.update(config['optimizer_params'])
optimizer = config['optimizer'](**opt_args)
scheduler = None

if config['scheduler'] is not None:
    sched_args = {'optimizer': optimizer}
    sched_args.update(config['scheduler_params'])
    scheduler = config['scheduler'](**sched_args)

# folder for save results
final_folder = dataset_name if version is None else '{}_{}'.format(dataset_name, version)
folder_name = os.path.join(base_model, final_folder)
folder_path = os.path.join('.', 'models', 'saved', folder_name)
print(folder_path)
print(base_model, model_name)

if not os.path.exists(folder_path):
    os.makedirs(folder_path)

print('Initiating training, models will be saved at {}'.format(folder_path))
# logs
with open(os.path.join(folder_path, 'training.log'), 'a+') as f:
        with redirect_stdout(f):
            print(model)
            # training metrics
            history, best_model, time_elapsed = train_model(model, criterion, optimizer, train_data, val_data,
                        epochs=epochs, batch_size=batch_size, shuffle_dataset=shuffle_dataset, scheduler=scheduler,
                        use_cuda=use_cuda)

# model save
model_path = os.path.join(folder_path, model_name)
print('Saving model {}'.format(model_path))
torch.save(best_model, model_path)

# metrics save
history_path = os.path.join(folder_path, 'history.csv')
save_history(history, file_path=history_path)

plot_history(history, folder_path=folder_path)